INSERT INTO products (name, sku, description, base_price, media_type, media_url, is_scene, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Summer Collection 2024', 'SCENE-001', 'Interactive video of our latest collection.', 0.00, 'image', 'assets/images/videocom.png', TRUE, 1, 'BrandX', 'Scene', 1, 1, '{}');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Vintage Belt', 'PROD-002', 'A high-quality vintage belt.', 163.99, 'image', 'https://placehold.co/400x400?text=Vintage+Belt', 199, 'H&M', 'Footwear', 1, 1, '{"Material": "Polyester", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (2, 'https://placehold.co/400x400?text=Vintage+Belt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (2, 'https://placehold.co/400x400?text=Vintage+Belt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (2, 'https://placehold.co/400x400?text=Vintage+Belt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (2, 2, 155.79);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (2, 5, 147.59);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Sunglasses', 'PROD-003', 'A high-quality cozy sunglasses.', 37.99, 'image', 'https://placehold.co/400x400?text=Cozy+Sunglasses', 69, 'Nike', 'Footwear', 10, 10, '{"Material": "Wool", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (3, 'https://placehold.co/400x400?text=Cozy+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (3, 'https://placehold.co/400x400?text=Cozy+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (3, 'https://placehold.co/400x400?text=Cozy+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (3, 20, 36.09);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (3, 50, 34.19);
INSERT INTO variants (product_id, type, value) VALUES (3, 'Size', 'M'), (3, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Essential T-Shirt', 'PROD-004', 'A high-quality essential t-shirt.', 166.99, 'image', 'https://placehold.co/400x400?text=Essential+T-Shirt', 268, 'Zara', 'Footwear', 10, 10, '{"Material": "Polyester", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (4, 'https://placehold.co/400x400?text=Essential+T-Shirt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (4, 'https://placehold.co/400x400?text=Essential+T-Shirt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (4, 'https://placehold.co/400x400?text=Essential+T-Shirt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (4, 20, 158.64);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (4, 50, 150.29);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Sunglasses', 'PROD-005', 'A high-quality cozy sunglasses.', 155.99, 'image', 'https://placehold.co/400x400?text=Cozy+Sunglasses', 454, 'Uniqlo', 'Women', 1, 1, '{"Material": "Leather", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (5, 'https://placehold.co/400x400?text=Cozy+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (5, 'https://placehold.co/400x400?text=Cozy+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (5, 'https://placehold.co/400x400?text=Cozy+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (5, 2, 148.19);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (5, 5, 140.39);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Scarf', 'PROD-006', 'A high-quality classic scarf.', 133.99, 'image', 'https://placehold.co/400x400?text=Classic+Scarf', 293, 'Uniqlo', 'Women', 1, 1, '{"Material": "Denim", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (6, 'https://placehold.co/400x400?text=Classic+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (6, 'https://placehold.co/400x400?text=Classic+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (6, 'https://placehold.co/400x400?text=Classic+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (6, 2, 127.29);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (6, 5, 120.59);
INSERT INTO variants (product_id, type, value) VALUES (6, 'Size', 'M'), (6, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Belt', 'PROD-007', 'A high-quality bold belt.', 169.99, 'image', 'https://placehold.co/400x400?text=Bold+Belt', 293, 'Nike', 'Men', 1, 1, '{"Material": "Cotton", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (7, 'https://placehold.co/400x400?text=Bold+Belt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (7, 'https://placehold.co/400x400?text=Bold+Belt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (7, 'https://placehold.co/400x400?text=Bold+Belt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (7, 2, 161.49);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (7, 5, 152.99);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Sunglasses', 'PROD-008', 'A high-quality urban sunglasses.', 97.99, 'image', 'https://placehold.co/400x400?text=Urban+Sunglasses', 458, 'Nike', 'Men', 1, 1, '{"Material": "Polyester", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (8, 'https://placehold.co/400x400?text=Urban+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (8, 'https://placehold.co/400x400?text=Urban+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (8, 'https://placehold.co/400x400?text=Urban+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (8, 2, 93.09);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (8, 5, 88.19);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Sunglasses', 'PROD-009', 'A high-quality urban sunglasses.', 193.99, 'image', 'https://placehold.co/400x400?text=Urban+Sunglasses', 465, 'Nike', 'Women', 1, 1, '{"Material": "Wool", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (9, 'https://placehold.co/400x400?text=Urban+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (9, 'https://placehold.co/400x400?text=Urban+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (9, 'https://placehold.co/400x400?text=Urban+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (9, 2, 184.29);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (9, 5, 174.59);
INSERT INTO variants (product_id, type, value) VALUES (9, 'Size', 'M'), (9, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Sleek Sneakers', 'PROD-010', 'A high-quality sleek sneakers.', 199.99, 'image', 'https://placehold.co/400x400?text=Sleek+Sneakers', 362, 'Adidas', 'Women', 5, 5, '{"Material": "Leather", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (10, 'https://placehold.co/400x400?text=Sleek+Sneakers+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (10, 'https://placehold.co/400x400?text=Sleek+Sneakers+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (10, 'https://placehold.co/400x400?text=Sleek+Sneakers+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (10, 10, 189.99);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (10, 25, 179.99);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Scarf', 'PROD-011', 'A high-quality classic scarf.', 54.99, 'image', 'https://placehold.co/400x400?text=Classic+Scarf', 402, 'H&M', 'Accessories', 10, 10, '{"Material": "Polyester", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (11, 'https://placehold.co/400x400?text=Classic+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (11, 'https://placehold.co/400x400?text=Classic+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (11, 'https://placehold.co/400x400?text=Classic+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (11, 20, 52.24);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (11, 50, 49.49);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Sneakers', 'PROD-012', 'A high-quality bold sneakers.', 160.99, 'image', 'https://placehold.co/400x400?text=Bold+Sneakers', 241, 'H&M', 'Accessories', 1, 1, '{"Material": "Cotton", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (12, 'https://placehold.co/400x400?text=Bold+Sneakers+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (12, 'https://placehold.co/400x400?text=Bold+Sneakers+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (12, 'https://placehold.co/400x400?text=Bold+Sneakers+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (12, 2, 152.94);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (12, 5, 144.89);
INSERT INTO variants (product_id, type, value) VALUES (12, 'Size', 'M'), (12, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic T-Shirt', 'PROD-013', 'A high-quality classic t-shirt.', 118.99, 'image', 'https://placehold.co/400x400?text=Classic+T-Shirt', 56, 'H&M', 'Women', 1, 1, '{"Material": "Wool", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (13, 'https://placehold.co/400x400?text=Classic+T-Shirt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (13, 'https://placehold.co/400x400?text=Classic+T-Shirt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (13, 'https://placehold.co/400x400?text=Classic+T-Shirt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (13, 2, 113.04);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (13, 5, 107.09);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Scarf', 'PROD-014', 'A high-quality bold scarf.', 45.99, 'image', 'https://placehold.co/400x400?text=Bold+Scarf', 293, 'Zara', 'Men', 1, 1, '{"Material": "Leather", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (14, 'https://placehold.co/400x400?text=Bold+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (14, 'https://placehold.co/400x400?text=Bold+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (14, 'https://placehold.co/400x400?text=Bold+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (14, 2, 43.69);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (14, 5, 41.39);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Sunglasses', 'PROD-015', 'A high-quality cozy sunglasses.', 67.99, 'image', 'https://placehold.co/400x400?text=Cozy+Sunglasses', 458, 'Adidas', 'Women', 1, 1, '{"Material": "Leather", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (15, 'https://placehold.co/400x400?text=Cozy+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (15, 'https://placehold.co/400x400?text=Cozy+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (15, 'https://placehold.co/400x400?text=Cozy+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (15, 2, 64.59);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (15, 5, 61.19);
INSERT INTO variants (product_id, type, value) VALUES (15, 'Size', 'M'), (15, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Jeans', 'PROD-016', 'A high-quality urban jeans.', 181.99, 'image', 'https://placehold.co/400x400?text=Urban+Jeans', 446, 'Gucci', 'Women', 1, 1, '{"Material": "Polyester", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (16, 'https://placehold.co/400x400?text=Urban+Jeans+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (16, 'https://placehold.co/400x400?text=Urban+Jeans+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (16, 'https://placehold.co/400x400?text=Urban+Jeans+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (16, 2, 172.89);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (16, 5, 163.79);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Belt', 'PROD-017', 'A high-quality urban belt.', 60.99, 'image', 'https://placehold.co/400x400?text=Urban+Belt', 270, 'Uniqlo', 'Footwear', 1, 1, '{"Material": "Wool", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (17, 'https://placehold.co/400x400?text=Urban+Belt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (17, 'https://placehold.co/400x400?text=Urban+Belt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (17, 'https://placehold.co/400x400?text=Urban+Belt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (17, 2, 57.94);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (17, 5, 54.89);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Scarf', 'PROD-018', 'A high-quality cozy scarf.', 152.99, 'image', 'https://placehold.co/400x400?text=Cozy+Scarf', 412, 'Uniqlo', 'Footwear', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (18, 'https://placehold.co/400x400?text=Cozy+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (18, 'https://placehold.co/400x400?text=Cozy+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (18, 'https://placehold.co/400x400?text=Cozy+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (18, 2, 145.34);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (18, 5, 137.69);
INSERT INTO variants (product_id, type, value) VALUES (18, 'Size', 'M'), (18, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Vintage Jacket', 'PROD-019', 'A high-quality vintage jacket.', 154.99, 'image', 'https://placehold.co/400x400?text=Vintage+Jacket', 499, 'Zara', 'Accessories', 1, 1, '{"Material": "Cotton", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (19, 'https://placehold.co/400x400?text=Vintage+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (19, 'https://placehold.co/400x400?text=Vintage+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (19, 'https://placehold.co/400x400?text=Vintage+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (19, 2, 147.24);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (19, 5, 139.49);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Jeans', 'PROD-020', 'A high-quality classic jeans.', 27.99, 'image', 'https://placehold.co/400x400?text=Classic+Jeans', 303, 'Uniqlo', 'Women', 1, 1, '{"Material": "Polyester", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (20, 'https://placehold.co/400x400?text=Classic+Jeans+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (20, 'https://placehold.co/400x400?text=Classic+Jeans+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (20, 'https://placehold.co/400x400?text=Classic+Jeans+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (20, 2, 26.59);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (20, 5, 25.19);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Sneakers', 'PROD-021', 'A high-quality urban sneakers.', 87.99, 'image', 'https://placehold.co/400x400?text=Urban+Sneakers', 273, 'Gucci', 'Men', 1, 1, '{"Material": "Cotton", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (21, 'https://placehold.co/400x400?text=Urban+Sneakers+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (21, 'https://placehold.co/400x400?text=Urban+Sneakers+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (21, 'https://placehold.co/400x400?text=Urban+Sneakers+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (21, 2, 83.59);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (21, 5, 79.19);
INSERT INTO variants (product_id, type, value) VALUES (21, 'Size', 'M'), (21, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Sleek Jeans', 'PROD-022', 'A high-quality sleek jeans.', 72.99, 'image', 'https://placehold.co/400x400?text=Sleek+Jeans', 457, 'Uniqlo', 'Women', 1, 1, '{"Material": "Polyester", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (22, 'https://placehold.co/400x400?text=Sleek+Jeans+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (22, 'https://placehold.co/400x400?text=Sleek+Jeans+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (22, 'https://placehold.co/400x400?text=Sleek+Jeans+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (22, 2, 69.34);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (22, 5, 65.69);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Jacket', 'PROD-023', 'A high-quality classic jacket.', 130.99, 'image', 'https://placehold.co/400x400?text=Classic+Jacket', 490, 'Gucci', 'Accessories', 1, 1, '{"Material": "Leather", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (23, 'https://placehold.co/400x400?text=Classic+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (23, 'https://placehold.co/400x400?text=Classic+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (23, 'https://placehold.co/400x400?text=Classic+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (23, 2, 124.44);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (23, 5, 117.89);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Sneakers', 'PROD-024', 'A high-quality classic sneakers.', 95.99, 'image', 'https://placehold.co/400x400?text=Classic+Sneakers', 52, 'Nike', 'Men', 5, 5, '{"Material": "Denim", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (24, 'https://placehold.co/400x400?text=Classic+Sneakers+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (24, 'https://placehold.co/400x400?text=Classic+Sneakers+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (24, 'https://placehold.co/400x400?text=Classic+Sneakers+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (24, 10, 91.19);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (24, 25, 86.39);
INSERT INTO variants (product_id, type, value) VALUES (24, 'Size', 'M'), (24, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Hat', 'PROD-025', 'A high-quality modern hat.', 151.99, 'image', 'https://placehold.co/400x400?text=Modern+Hat', 249, 'H&M', 'Women', 10, 10, '{"Material": "Cotton", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (25, 'https://placehold.co/400x400?text=Modern+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (25, 'https://placehold.co/400x400?text=Modern+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (25, 'https://placehold.co/400x400?text=Modern+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (25, 20, 144.39);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (25, 50, 136.79);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Essential Bag', 'PROD-026', 'A high-quality essential bag.', 142.99, 'image', 'https://placehold.co/400x400?text=Essential+Bag', 198, 'Gucci', 'Footwear', 1, 1, '{"Material": "Leather", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (26, 'https://placehold.co/400x400?text=Essential+Bag+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (26, 'https://placehold.co/400x400?text=Essential+Bag+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (26, 'https://placehold.co/400x400?text=Essential+Bag+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (26, 2, 135.84);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (26, 5, 128.69);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy T-Shirt', 'PROD-027', 'A high-quality cozy t-shirt.', 98.99, 'image', 'https://placehold.co/400x400?text=Cozy+T-Shirt', 274, 'Nike', 'Footwear', 1, 1, '{"Material": "Polyester", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (27, 'https://placehold.co/400x400?text=Cozy+T-Shirt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (27, 'https://placehold.co/400x400?text=Cozy+T-Shirt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (27, 'https://placehold.co/400x400?text=Cozy+T-Shirt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (27, 2, 94.04);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (27, 5, 89.09);
INSERT INTO variants (product_id, type, value) VALUES (27, 'Size', 'M'), (27, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Sneakers', 'PROD-028', 'A high-quality modern sneakers.', 101.99, 'image', 'https://placehold.co/400x400?text=Modern+Sneakers', 201, 'Adidas', 'Accessories', 1, 1, '{"Material": "Leather", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (28, 'https://placehold.co/400x400?text=Modern+Sneakers+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (28, 'https://placehold.co/400x400?text=Modern+Sneakers+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (28, 'https://placehold.co/400x400?text=Modern+Sneakers+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (28, 2, 96.89);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (28, 5, 91.79);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Belt', 'PROD-029', 'A high-quality cozy belt.', 163.99, 'image', 'https://placehold.co/400x400?text=Cozy+Belt', 422, 'Gucci', 'Men', 10, 10, '{"Material": "Leather", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (29, 'https://placehold.co/400x400?text=Cozy+Belt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (29, 'https://placehold.co/400x400?text=Cozy+Belt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (29, 'https://placehold.co/400x400?text=Cozy+Belt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (29, 20, 155.79);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (29, 50, 147.59);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Jacket', 'PROD-030', 'A high-quality classic jacket.', 195.99, 'image', 'https://placehold.co/400x400?text=Classic+Jacket', 260, 'Zara', 'Men', 1, 1, '{"Material": "Wool", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (30, 'https://placehold.co/400x400?text=Classic+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (30, 'https://placehold.co/400x400?text=Classic+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (30, 'https://placehold.co/400x400?text=Classic+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (30, 2, 186.19);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (30, 5, 176.39);
INSERT INTO variants (product_id, type, value) VALUES (30, 'Size', 'M'), (30, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Jacket', 'PROD-031', 'A high-quality modern jacket.', 43.99, 'image', 'https://placehold.co/400x400?text=Modern+Jacket', 217, 'Nike', 'Men', 5, 5, '{"Material": "Cotton", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (31, 'https://placehold.co/400x400?text=Modern+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (31, 'https://placehold.co/400x400?text=Modern+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (31, 'https://placehold.co/400x400?text=Modern+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (31, 10, 41.79);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (31, 25, 39.59);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Hat', 'PROD-032', 'A high-quality urban hat.', 39.99, 'image', 'https://placehold.co/400x400?text=Urban+Hat', 200, 'Gucci', 'Women', 10, 10, '{"Material": "Wool", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (32, 'https://placehold.co/400x400?text=Urban+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (32, 'https://placehold.co/400x400?text=Urban+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (32, 'https://placehold.co/400x400?text=Urban+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (32, 20, 37.99);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (32, 50, 35.99);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Watch', 'PROD-033', 'A high-quality modern watch.', 128.99, 'image', 'https://placehold.co/400x400?text=Modern+Watch', 233, 'Zara', 'Accessories', 5, 5, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (33, 'https://placehold.co/400x400?text=Modern+Watch+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (33, 'https://placehold.co/400x400?text=Modern+Watch+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (33, 'https://placehold.co/400x400?text=Modern+Watch+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (33, 10, 122.54);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (33, 25, 116.09);
INSERT INTO variants (product_id, type, value) VALUES (33, 'Size', 'M'), (33, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Sleek Hat', 'PROD-034', 'A high-quality sleek hat.', 116.99, 'image', 'https://placehold.co/400x400?text=Sleek+Hat', 147, 'Zara', 'Men', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (34, 'https://placehold.co/400x400?text=Sleek+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (34, 'https://placehold.co/400x400?text=Sleek+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (34, 'https://placehold.co/400x400?text=Sleek+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (34, 2, 111.14);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (34, 5, 105.29);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Sunglasses', 'PROD-035', 'A high-quality bold sunglasses.', 175.99, 'image', 'https://placehold.co/400x400?text=Bold+Sunglasses', 304, 'H&M', 'Accessories', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (35, 'https://placehold.co/400x400?text=Bold+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (35, 'https://placehold.co/400x400?text=Bold+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (35, 'https://placehold.co/400x400?text=Bold+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (35, 2, 167.19);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (35, 5, 158.39);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Scarf', 'PROD-036', 'A high-quality urban scarf.', 111.99, 'image', 'https://placehold.co/400x400?text=Urban+Scarf', 252, 'Nike', 'Women', 1, 1, '{"Material": "Wool", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (36, 'https://placehold.co/400x400?text=Urban+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (36, 'https://placehold.co/400x400?text=Urban+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (36, 'https://placehold.co/400x400?text=Urban+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (36, 2, 106.39);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (36, 5, 100.79);
INSERT INTO variants (product_id, type, value) VALUES (36, 'Size', 'M'), (36, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Scarf', 'PROD-037', 'A high-quality modern scarf.', 56.99, 'image', 'https://placehold.co/400x400?text=Modern+Scarf', 307, 'Uniqlo', 'Women', 1, 1, '{"Material": "Wool", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (37, 'https://placehold.co/400x400?text=Modern+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (37, 'https://placehold.co/400x400?text=Modern+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (37, 'https://placehold.co/400x400?text=Modern+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (37, 2, 54.14);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (37, 5, 51.29);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Jacket', 'PROD-038', 'A high-quality classic jacket.', 142.99, 'image', 'https://placehold.co/400x400?text=Classic+Jacket', 499, 'Uniqlo', 'Women', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (38, 'https://placehold.co/400x400?text=Classic+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (38, 'https://placehold.co/400x400?text=Classic+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (38, 'https://placehold.co/400x400?text=Classic+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (38, 2, 135.84);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (38, 5, 128.69);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Sleek Scarf', 'PROD-039', 'A high-quality sleek scarf.', 49.99, 'image', 'https://placehold.co/400x400?text=Sleek+Scarf', 352, 'Nike', 'Women', 1, 1, '{"Material": "Leather", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (39, 'https://placehold.co/400x400?text=Sleek+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (39, 'https://placehold.co/400x400?text=Sleek+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (39, 'https://placehold.co/400x400?text=Sleek+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (39, 2, 47.49);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (39, 5, 44.99);
INSERT INTO variants (product_id, type, value) VALUES (39, 'Size', 'M'), (39, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Jacket', 'PROD-040', 'A high-quality bold jacket.', 190.99, 'image', 'https://placehold.co/400x400?text=Bold+Jacket', 137, 'Gucci', 'Accessories', 1, 1, '{"Material": "Polyester", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (40, 'https://placehold.co/400x400?text=Bold+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (40, 'https://placehold.co/400x400?text=Bold+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (40, 'https://placehold.co/400x400?text=Bold+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (40, 2, 181.44);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (40, 5, 171.89);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Vintage Jacket', 'PROD-041', 'A high-quality vintage jacket.', 61.99, 'image', 'https://placehold.co/400x400?text=Vintage+Jacket', 213, 'Nike', 'Accessories', 10, 10, '{"Material": "Wool", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (41, 'https://placehold.co/400x400?text=Vintage+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (41, 'https://placehold.co/400x400?text=Vintage+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (41, 'https://placehold.co/400x400?text=Vintage+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (41, 20, 58.89);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (41, 50, 55.79);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Hat', 'PROD-042', 'A high-quality bold hat.', 146.99, 'image', 'https://placehold.co/400x400?text=Bold+Hat', 187, 'Uniqlo', 'Accessories', 10, 10, '{"Material": "Denim", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (42, 'https://placehold.co/400x400?text=Bold+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (42, 'https://placehold.co/400x400?text=Bold+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (42, 'https://placehold.co/400x400?text=Bold+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (42, 20, 139.64);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (42, 50, 132.29);
INSERT INTO variants (product_id, type, value) VALUES (42, 'Size', 'M'), (42, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Sleek T-Shirt', 'PROD-043', 'A high-quality sleek t-shirt.', 159.99, 'image', 'https://placehold.co/400x400?text=Sleek+T-Shirt', 329, 'Nike', 'Footwear', 1, 1, '{"Material": "Cotton", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (43, 'https://placehold.co/400x400?text=Sleek+T-Shirt+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (43, 'https://placehold.co/400x400?text=Sleek+T-Shirt+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (43, 'https://placehold.co/400x400?text=Sleek+T-Shirt+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (43, 2, 151.99);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (43, 5, 143.99);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Sunglasses', 'PROD-044', 'A high-quality modern sunglasses.', 26.99, 'image', 'https://placehold.co/400x400?text=Modern+Sunglasses', 379, 'Gucci', 'Men', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (44, 'https://placehold.co/400x400?text=Modern+Sunglasses+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (44, 'https://placehold.co/400x400?text=Modern+Sunglasses+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (44, 'https://placehold.co/400x400?text=Modern+Sunglasses+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (44, 2, 25.64);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (44, 5, 24.29);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Urban Hat', 'PROD-045', 'A high-quality urban hat.', 190.99, 'image', 'https://placehold.co/400x400?text=Urban+Hat', 228, 'Adidas', 'Footwear', 1, 1, '{"Material": "Denim", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (45, 'https://placehold.co/400x400?text=Urban+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (45, 'https://placehold.co/400x400?text=Urban+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (45, 'https://placehold.co/400x400?text=Urban+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (45, 2, 181.44);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (45, 5, 171.89);
INSERT INTO variants (product_id, type, value) VALUES (45, 'Size', 'M'), (45, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Cozy Jacket', 'PROD-046', 'A high-quality cozy jacket.', 170.99, 'image', 'https://placehold.co/400x400?text=Cozy+Jacket', 433, 'Gucci', 'Men', 1, 1, '{"Material": "Cotton", "Fit": "Regular", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (46, 'https://placehold.co/400x400?text=Cozy+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (46, 'https://placehold.co/400x400?text=Cozy+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (46, 'https://placehold.co/400x400?text=Cozy+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (46, 2, 162.44);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (46, 5, 153.89);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Bold Hat', 'PROD-047', 'A high-quality bold hat.', 82.99, 'image', 'https://placehold.co/400x400?text=Bold+Hat', 283, 'H&M', 'Accessories', 10, 10, '{"Material": "Leather", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (47, 'https://placehold.co/400x400?text=Bold+Hat+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (47, 'https://placehold.co/400x400?text=Bold+Hat+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (47, 'https://placehold.co/400x400?text=Bold+Hat+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (47, 20, 78.84);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (47, 50, 74.69);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Modern Jeans', 'PROD-048', 'A high-quality modern jeans.', 35.99, 'image', 'https://placehold.co/400x400?text=Modern+Jeans', 352, 'Gucci', 'Accessories', 5, 5, '{"Material": "Denim", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (48, 'https://placehold.co/400x400?text=Modern+Jeans+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (48, 'https://placehold.co/400x400?text=Modern+Jeans+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (48, 'https://placehold.co/400x400?text=Modern+Jeans+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (48, 10, 34.19);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (48, 25, 32.39);
INSERT INTO variants (product_id, type, value) VALUES (48, 'Size', 'M'), (48, 'Size', 'L');
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Essential Scarf', 'PROD-049', 'A high-quality essential scarf.', 200.99, 'image', 'https://placehold.co/400x400?text=Essential+Scarf', 140, 'Zara', 'Men', 1, 1, '{"Material": "Wool", "Fit": "Slim", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (49, 'https://placehold.co/400x400?text=Essential+Scarf+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (49, 'https://placehold.co/400x400?text=Essential+Scarf+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (49, 'https://placehold.co/400x400?text=Essential+Scarf+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (49, 2, 190.94);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (49, 5, 180.89);
INSERT INTO products (name, sku, description, base_price, media_type, thumbnail_url, stock_quantity, brand, category, moq, qty_step, attributes) VALUES ('Classic Jacket', 'PROD-050', 'A high-quality classic jacket.', 73.99, 'image', 'https://placehold.co/400x400?text=Classic+Jacket', 76, 'Gucci', 'Women', 1, 1, '{"Material": "Leather", "Fit": "Oversized", "Year": "2024"}');
INSERT INTO product_gallery (product_id, image_url) VALUES (50, 'https://placehold.co/400x400?text=Classic+Jacket+1');
INSERT INTO product_gallery (product_id, image_url) VALUES (50, 'https://placehold.co/400x400?text=Classic+Jacket+2');
INSERT INTO product_gallery (product_id, image_url) VALUES (50, 'https://placehold.co/400x400?text=Classic+Jacket+3');
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (50, 2, 70.29);
INSERT INTO product_tier_prices (product_id, min_qty, unit_price) VALUES (50, 5, 66.59);
INSERT INTO hotspots (parent_product_id, target_product_id, position_x, position_y) VALUES (1, 2, 25.0, 40.0), (1, 3, 50.0, 60.0), (1, 4, 75.0, 30.0);
